# Generated by Django 3.2.9 on 2021-11-27 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movielist_app', '0003_watchlist_platfrom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='platfrom',
            new_name='platform',
        ),
    ]
